AuthApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", register, name='register'),
    path("login", login_view, name='login'),
    path('logout', logout_view, name='logout'),
]

application/urls.py
from django.urls import path
from .views import *

app_name = 'application'

urlpatterns = [
    path('home/', home_view, name='home'),
    path('project-feature-add', project_feature_add_view, name='project-feature-add'),
    path('edit_view/<int:id>/', edit_view, name='edit_view'),
    path('delete_view/<int:id>/', delete_view, name='delete_view'),
    path('download_view/', download_view, name='download_view'),
    path('redesign-schema/', correctDB_view, name="correctDB_view"),
    path('save-response', save_response, name="save_response")
]

db_design_with_chatgpt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('AuthApp.urls')),
    path('application/', include('application.urls')),
]

templates/base.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="../static/assets/images/favicon.ico">
    <title>Auth System - {% block title %}{% endblock title %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/sign-in/">
    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href=" {% static 'assets/dist/css/signin.css' %}" rel="stylesheet">
    <link href=" {% static 'assets/dist/css/auth.css' %}" rel="stylesheet">
    <link href=" {% static 'assets/dist/css/loading.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock css %}
</head>

<body>
    <div class="loading" id="my-loader" style="display: none;">Loading&#8230;</div>
    {% block content %}
    {% endblock content %}
</body>

</html>

templates/correct_db.html
{% extends "index.html" %} {% load static %} {% load crispy_forms_tags %}
{%block title %} Home {% endblock title %} 
{% block css %}
<style>
  .h1-text {
    font-size: 26px;
    font-family: "Inter";
  }

  .panel-heading {
    cursor: pointer;
  }

  .panel-title {
    font-weight: bold;
  }

  .editable-title {
    display: inline-block;
    cursor: pointer;
  }

  .editable-title input {
    border: none;
    background: transparent;
    font-weight: bold;
  }

  table {
    border-collapse: collapse;
    width: 100%;
  }

  th,
  td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
  }

  td input[type="text"] {
    border: none;
    width: 100%;
    background-color: transparent;
  }

  .scrollable {
    overflow-y: scroll;
    height: 330px;
  }
</style>
{% endblock css %} 
{% block content %}
<div class="loading" id="my-loader" style="display: none;">Loading&#8230;</div>
<div class="px-5">
  <div class="row mt-3">
    <div class="col-9"></div>
    <div class="col-lg-3 col-md-3 col-sm-6">
      <a href="{% url 'application:home' %}" role="button" class="btn btn-sm btn-dark float-right mb-3">
        <i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;Back
      </a>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-4 c4-sm-4">
      <div class="card mb-3">
        <div class="card-body p-2">
          <form class="form-signin" method="post">
            <div class="row d-flex justify-content-center align-items-center overflow-hidden">
              <div class="form-group m-0 col-12 mb-2">
                <label for="feature_change">Select Sql File</label>
                <input type="file" name="  sql_file" id="sql_file" placeholder="Select File" class="form-control"/>
                <span id="sql_file" class="my-2 text-danger"></span>
              </div>
              <div class="form-group m-0 col-12 mb-2">
                <label for="feature_change">Feature</label>
                <textarea class="form-control" placeholder="Describe Changes" name="feature_change" id="feature_change" cols="30" rows="11"></textarea>
                <span id="feature_change" class="my-2 text-danger"></span>
              </div>
              <div class="form-group m-0 col-12 d-flex">
                <button id="correct-sql" class="w-100 btn btn-md btn-primary mr-2 align-items-center" type="button">
                  Generate
                </button>
                <button id="btn-reset" class="w-100 btn btn-md btn-danger align-items-center" type="reset">
                  Reset
                </button>
                <div id="loader" style="display: none;">
                  <img src="{% static 'assets/images/30.gif' %}" width="150px" height="30px" alt="loader"/>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8">
      <div class="card">
        <div class="card-header bg-secondary text-white">
          <div class="w-100 d-flex justify-content-between align-items-center">
            <h5 class="m-0">SQL Editor</h5>
            <button id="download-sql" class="btn btn-sm btn-primary pull-right" title="Download File" style="display: none;">
              Download SQL
            </button>
          </div>
        </div>
        <div class="card-body" style="padding: 0.7em;">
          <div class="form-group mb-1">
            <textarea name="sqlEditor" id="sqlEditor" cols="30" spellcheck="false" rows="15" class="form-control"></textarea>
            <span id="projectFeatureError" class="my-2 text-danger"></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %} 
{% block cjs %}

<script>
  let finalResponse;
  var myData = [];
  let project_id = 0;

  $(document).ready(function () {
    $("#loader").hide();
    $("#download-sql").hide();

    //generate response
    $("#correct-sql").on("click", function () {
      $("#my-loader").show()
      var fileInput = document.getElementById("sql_file");
      var file = fileInput.files[0];
      
      if(file){
        const reader = new FileReader();

        reader.onload = function (e) {
          const fileData = e.target.result;
          if (fileData) {
            $.ajax({
              url: "{% url 'application:correctDB_view' %}",
              method: "POST",
              data: JSON.stringify({
                sql_file: fileData,
                feature_change: $('#feature_change').val().trim()
              }),
              processData: false,
              ontentType: false,
              beforeSend: function (xhr, settings) {
                $("#loader").show();
                $("#download-sql").hide();
                $("#btn-submit").hide();
                $("#btn-reset").hide();
                $("#correct-sql").hide();
                $("#sqlEditor").val("");
                function getCookie(name) {
                  var cookieValue = null;
                  if (document.cookie && document.cookie != "") {
                    var cookies = document.cookie.split(";");
                    for (var i = 0; i < cookies.length; i++) {
                      var cookie = jQuery.trim(cookies[i]);
                      // Does this cookie string begin with the name we want?
                      if (cookie.substring(0, name.length + 1) == name + "=") {
                        cookieValue = decodeURIComponent(
                          cookie.substring(name.length + 1)
                        );
                        break;
                      }
                    }
                  }
                  return cookieValue;
                }
                if (
                  !(
                    /^http:.*/.test(settings.url) ||
                    /^https:.*/.test(settings.url)
                  )
                ) {
                  // Only send the token to relative URLs i.e. locally.
                  xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
                }
              },
              success: function (response) {
                $("#loader").hide();
                $("#download-sql").show();
                $("#btn-submit").show();
                $("#btn-reset").show();
                $("#correct-sql").show();

                try {
                  const resp = JSON.parse(response)
                  alert(resp.message)
                } catch (error) {
                  response = response?.split(":")[1] ? response?.split(":")[1] : response?.replace(":", "")
                  $("#sqlEditor").val(sqlFormatter.format(response));
                }
                $('#my-loader').hide()
              },
            });
          }
        };
        reader.readAsText(file);
      }else{
        Swal.fire('Select SQL File first.!', '', 'error')
      }
    });

    function downloadFile(filename, content) {
      const element = document.createElement('a');
      const blob = new Blob([content], { type: 'plain/text' });
      const fileUrl = URL.createObjectURL(blob);
      
      element.setAttribute('href', fileUrl);
      element.setAttribute('download', filename);
      element.style.display = 'none';
      
      document.body.appendChild(element);
      element.click();
      
      document.body.removeChild(element);
    };

    $("#download-sql").click(() => {
      downloadFile("converted.sql", $("#sqlEditor").val())
    });
  });
</script>
{% endblock cjs %}

templates/home.html
{% extends "index.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Dashboard
{% endblock title %}

{% block css %}
<style>
    .h1-text {
        font-size: 26px;
        font-family: 'Inter';
    }

    .cust-table td {
        padding: 0em 0.5em;
        vertical-align: middle;
    }

    .action-btns{
        text-decoration: none !important;
    }
</style>
{% endblock css %}

{% block content %}
<div class="loading" id="my-loader" style="display: none;">Loading&#8230;</div>
<div class="px-5">
    <div class="row mt-3">
        <div class="col-lg-8 col-md-8 col-sm-8 d-flex align-items-center">
            <h5 class="m-0 h1-text">Project Details</h5>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="w-100 d-flex align-items-center justify-content-end">
                <a href="{% url 'application:project-feature-add' %}" role="button" class="w-100 mb-0 mr-1 btn btn-sm btn-primary float-right">Add New Project</a>
                <a href="{% url 'application:correctDB_view' %}" role="button" class="w-100 mb-0 btn btn-sm btn-primary float-right">Correct Existing Schema</a>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-lg-12 col-md-12 col-sm-6">
            <div class="card">
                <div class="card-body table-responsive">
                    <div class="mt-3">
                        <div class="row">
                            <div class="col-md-12">
                                {% if messages %}
                                {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <table class="table table-striped table-hover table-bordered cust-table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Project Title</th>
                                <th>Created At</th>
                                <th>Download File</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if data %}
                            {% for value in data %}
                            <tr>
                                <td>{{ forloop.counter0|add:data.start_index}}</td>
                                <td class="text-wrap">{{value.project_title}}</td>
                                <td>{{value.created_at|date:'d-m-Y P'}}</td>
                                <td>
                                    <ul class="navbar-nav mr-3">
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" class="btn btn-link" data-toggle="dropdown" aria-expanded="false">
                                                {{value.project_title}}
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <a class="dropdown-item download-excl" data-id="{{value.id}}" href="#">Excel</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item download-sql" data-id="{{value.id}}" href="#">SQL</a>
                                            </div>
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    <a href="{% url 'application:edit_view' value.id %}" class="action-btns">
                                        Edit
                                    </a>
                                    &nbsp;&nbsp;
                                    <a href="{% url 'application:delete_view' value.id %}" class="action-btns text-danger" onclick="return confirm('Are you Sure To Delete Project Data ?')">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="5" class="text-center p-3">No Project data are available.</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                    <div class="mt-3">
                        {% if data.has_other_pages %}
                        <ul class="pagination pull-right">
                            {% if data.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ data.previous_page_number }}">&laquo;</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
                            {% endif %}
                            {% for i in data.paginator.page_range %}
                            {% if data.number == i %}
                            <li class="page-item active"><span class="page-link">{{ i }} <span
                                        class="sr-only">(current)</span></span></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if data.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">&raquo;</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block cjs %}
<script>
    $(document).ready(function () {
        function dataURLtoFile(dataurl, filename) {
            var arr = dataurl.split(','),
                mime = arr[0].match(/:(.*?);/)[1],
                bstr = atob(arr[arr.length - 1]), 
                n = bstr.length, 
                u8arr = new Uint8Array(n);
            while(n--){
                u8arr[n] = bstr.charCodeAt(n);
            }
            return new File([u8arr], filename, {type:mime});
        }

        $(document).on("click", ".download-excl", (e) => {
            $.ajax({
                url: "{% url 'application:download_view' %}",
                method: "POST",
                data: JSON.stringify({
                    file_type: "excel",
                    project_id: $(e.target)?.data('id')
                }),
                beforeSend: function (xhr, settings) {
                    $("#my-loader").show()
                    function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != "") {
                        var cookies = document.cookie.split(";");
                        for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == name + "=") {
                            cookieValue = decodeURIComponent(
                            cookie.substring(name.length + 1)
                            );
                            break;
                        }
                        }
                    }
                    return cookieValue;
                    }
                    if (
                    !(
                        /^http:.*/.test(settings.url) ||
                        /^https:.*/.test(settings.url)
                    )
                    ) {
                    // Only send the token to relative URLs i.e. locally.
                    xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
                    }
                },
                success: function (response) {
                    var base64Data = response;
                    var fileName = 'example.xlsx';

                    var downloadLink = document.createElement('a');
                    downloadLink.href = 'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,' + base64Data;
                    downloadLink.download = fileName;

                    document.body.appendChild(downloadLink);
                    downloadLink.click();
                    document.body.removeChild(downloadLink);
                    $("#my-loader").hide()
                }
            });
        });

        function downloadFile(filename, content) {
            const element = document.createElement('a');
            const blob = new Blob([content], { type: 'plain/text' });
            const fileUrl = URL.createObjectURL(blob);
            
            element.setAttribute('href', fileUrl);
            element.setAttribute('download', filename);
            element.style.display = 'none';
            
            document.body.appendChild(element);
            element.click();
            
            document.body.removeChild(element);
        };

        $(document).on("click", ".download-sql", (e) => {
            $.ajax({
                url: "{% url 'application:download_view' %}",
                method: "POST",
                data: JSON.stringify({
                    file_type: "sql",
                    project_id: $(e.target)?.data('id')
                }),
                beforeSend: function (xhr, settings) {
                    $("#my-loader").show()
                    function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != "") {
                        var cookies = document.cookie.split(";");
                        for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == name + "=") {
                            cookieValue = decodeURIComponent(
                            cookie.substring(name.length + 1)
                            );
                            break;
                        }
                        }
                    }
                    return cookieValue;
                    }
                    if (
                    !(
                        /^http:.*/.test(settings.url) ||
                        /^https:.*/.test(settings.url)
                    )
                    ) {
                    // Only send the token to relative URLs i.e. locally.
                    xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
                    }
                },
                success: function (response) {
                    downloadFile("download.sql", sqlFormatter.format(response))
                    $("#my-loader").hide()
                }
            });
        });
    });
</script>
{% endblock cjs %}

templates/index.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@200..900&display=swap">
    <link href=" {% static 'assets/dist/css/loading.css' %}" rel="stylesheet">
    <title>Auto Chat GPT System - {% block title %}{% endblock title %}</title>
    {% block css %}
    {% endblock css %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'application:home' %}">DB Design</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'application:home' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
            <ul class="navbar-nav mr-3">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-capitalize" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-expanded="false">{{user.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">My Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/sql-formatter/dist/sql-formatter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.6.0/jszip.min.js"></script>

    {% block cjs %}
    {% endblock cjs %}
</body>

</html>